name: Test

on:
  push:
    paths-ignore:
      - "LICENSE"
    branches:
      - "main"
  pull_request_review:
    types: [submitted, edited]
  workflow_dispatch:

jobs:
  test:
    runs-on: 'ubuntu-20.04'
    steps:
      - run: echo 'Hello'

